### ISSUE TITLE
feature: automatic generated web admin ui

### ISSUE THREAD

**Issue by ilovenwd** [interagent/heroics#36]
The auto generated CLI is already very useful for admin tasks for a API.
But a simple web based admin ui (GUI) may be more helpful.
Changes are:
- options in CLI to forms in GUI with validation
- method in CLI to admin tasks/buttons/links in GUI
- resource in CLI to admin page in GUI

GUI is less error prone and more helpful for non-tech people.

**Comment by schneems** [comment]
Sorry for the extreme delay. I like the idea of simplifying API access for power users via a web app. I wonder if it's necessary to tightly couple it to this codebase or not though. I think a good path forward would be to make another third party library that utilizes Heroics to generate such a site. If it's popular then we can re-visit a deeper integration.
