### ISSUE TITLE
'multi word' objects cause errors

### ISSUE THREAD

**Issue by neilmiddleton** [interagent/heroics#47]
I have two objects, InboundEmail and SavedSearch, both of which get generated into a client just fine, however when executing calls to these I see errors which point and an incorrect name construction:

```bash
[4] (main)> sa.inbound_email.find('foo')
NoMethodError: undefined method `inbound-email' for #<Heroics::Client url="https://<redacted>.herokuapp.com">
from /Users/neil/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/heroics-0.0.12/lib/heroics/client.rb:23:in `method_missing'
[5] (main)> sa.saved_search.list
NoMethodError: undefined method `saved-search' for #<Heroics::Client url="https://<redacted>.herokuapp.com">
from /Users/neil/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/heroics-0.0.12/lib/heroics/client.rb:23:in `method_missing'
```

**Comment by neilmiddleton** [comment]
Looking at this the problem seems to lie in the lookup into [`@resources` in client.rb](https://github.com/interagent/heroics/blob/master/lib/heroics/client.rb#L21).  

Weirdly, `sa.inbound_email` exists, it's only when running find does the above exception occur.

I'm stuck on this now, as I'm not at all clear on how this code is working.

**Comment by geemus** [comment]
@neilmiddleton I'm not sure at a glance, could you point me to the schema in question?

**Comment by neilmiddleton** [comment]
@geemus this is support-api

**Comment by geemus** [comment]
Ah. We expect/assume that hrefs will be dasherized instead of underscored. The [gsub](https://github.com/interagent/heroics/blob/master/lib/heroics/client.rb#L20) provides for that conversion (as ruby method name calling generally does not allow dashes). Does that help/make sense?

**Comment by neilmiddleton** [comment]
I've dasherized the hrefs in question but am still seeing issues.

```
NoMethodError: undefined method `inbound-email' for #<Heroics::Client url="...
```

**Comment by geemus** [comment]
Afraid I lack some context/knowledge here also.

@jkakar - maybe you know off hand what we might be missing?

**Comment by jkakar** [comment]
I've poked about and things look fine to me...?  I don't understand
how `client.inbound_email` could work but `client.inbound_email.find`
could fail in the way @neilmiddleton has reported...?
