### ISSUE TITLE
Add `connect_url` or similar method to generated clients

### ISSUE THREAD

**Issue by danp** [interagent/heroics#52]
If I have a full URL with userinfo in it, it's a bit hard to use with `Foo.connect` right now:

``` ruby
uri = URL.parse(url)
client = Foo.connect(uri.password, user: uri.user, url: url)
```

I wish I could do:

``` ruby
client = Foo.connect(url)
```

and have everything come from the URL. I understand overloading `connect` wouldn't be great. What about `connect_url`? Related `connect_oauth_url` and `connect_token_url` methods might be useful too.

**Comment by geemus** [comment]
:+1: sounds legit. I would agree that not overloading is probably better, the connect methods naming you mention seems reasonable.

**Comment by schneems** [comment]
I think that could also be useful, however, there's been no movement on here for 5 years. Let's close this feature request for now.
