### ISSUE TITLE
Support 204 No Content responses

### ISSUE THREAD

**Issue by nwjsmith** [interagent/heroics#57]
I'm currently building an API that adheres to the JSON API spec, which specifies that successful DELETE requests respond with 204 No Content. Heroics generates a client that throws an error when it receives that response.

Is it reasonable to just add `204` to the list of acceptable response codes here: https://github.com/interagent/heroics/blob/master/lib/heroics/link.rb#L62 ?

**Comment by geemus** [comment]
Hey, that is probably fine. Did you have further questions/concerns?

**Comment by nwjsmith** [comment]
@geemus awesome, PR is up here: https://github.com/interagent/heroics/pull/58
