### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nwjsmith** [interagent/heroics#60]
Could a new release of the heroics gem be cut? There have been quite a few changes since the last release.

**Comment by geemus** [comment]
@nwjsmith thanks for the prod, I'll see what I can do.

@jkakar I'm happy to push this out, but looks like you are the only gem owner at present. If you add me and let me know I'd be happy to take it the rest of the way. Thanks!

**Comment by kch** [comment]
:+1:

**Comment by jkakar** [comment]
I just published a [heroics 0.0.13](https://rubygems.org/gems/heroics/versions/0.0.13) gem.

**Comment by jkakar** [comment]
@geemus I added you as an owner:

```
$ gem owner --add geemus@gmail.com heroics
Owner added successfully.
Owners for gem: heroics
- geemus@gmail.com
- jkakar@kakar.ca
```

**Comment by brandur** [comment]
@jkakar While we're at it, do you mind adding me as well? A little
redundancy can't hurt.

``` sh
gem owner --add brandur@mutelight.org heroics
```

**Comment by jkakar** [comment]
@brandur Done!

```
$ gem owner --add brandur@mutelight.org heroics
Owner added successfully.
Owners for gem: heroics
- brandur@mutelight.org
- geemus@gmail.com
- jkakar@kakar.ca
```

**Comment by brandur** [comment]
@jkakar Thank-you!

**Comment by nwjsmith** [comment]
Thanks!
