### ISSUE TITLE
Exposed ETags

### ISSUE THREAD

**Issue by neilmiddleton** [interagent/heroics#63]
If I make a request using Heroics I get the resource, but the ETag appears to be eaten as only the body is returned.  This makes it impossible to grab the ETag returned by the request if I want to send it back on a PATCH request (which I also can't do)...

...or I'm missing something.

**Comment by uberjay** [comment]
Yeah, this is something I've been thinking about recently. For better or worse, heroics completely hides the per-request HTTP details from the client. It'd be nice to have a way to specify/override execution params on a per-request basis.

**Comment by schneems** [comment]
I would like to add two things:

- A mechanism for making raw requests i.e. passing a manual/custom path/endpoint or headers or body etc.
- A mechanism for retrieving the raw response back from the server.

As is this feature request is 4-5 years old. No one is actively working on it. Let's close it out for now. If any of us have a more specific idea or example code of what the API design might look like, or possibly a PR to kickstart discussion then we can continue there.
