### ISSUE TITLE
I dont have definitions in my json schemas

### ISSUE THREAD

**Issue by ailjushkin** [interagent/heroics#67]
My json schemas have not definitions at all and as I can see now, your code does not support other schemas, without definitions section. You should point to this problem in your readme section in this repository. By the problem what I mean is that I have only json schemas which have: 
- type
- properties
- required
- oneOf 
- pattern

jsonschema specific objects, nothing more.

**Comment by geemus** [comment]
The presumption we work under is that definitions includes a list of resources, which is done as a simplifying step. This way we are able to work on each resource as it's own schema and then use `prmd combine` to pull them together into a combined schema, which we have found is a bit easier way to work. I tried to document those to make this at least somewhat clearer by calling out which actions operate on "combined" schemas vs individual, but I would certainly welcome PRs or suggestions about how we can further improve the situation. Thanks!

**Comment by schneems** [comment]
This issue is 5 years old. If you've got specific documentation suggestions feel free to open PRs.
