### ISSUE TITLE
ruby_name not actually naming the client Ruby method names

### ISSUE THREAD

**Issue by mathias** [interagent/heroics#83]
I thought that with https://github.com/interagent/heroics/blob/master/lib/heroics/naming.rb#L10 and making it configurable through the `Configuration` class, we could control how names in our JSON Schema get turned into ruby method names in the generated client Ruby file. Turns out, it isn't doing that -- I suspect that there's a number of places in the code where we're just doing `.gsub(/-/, '_')` on the fly.

This can be recreated by adding this to the example dir project `example-client-configuration.rb`:

```ruby
  config.ruby_name_replacement_patterns = { /[A-Ya-y]+/ => 'z' }

```
Which should result in some interesting Ruby method names! (All z's)
And then running this in the `example` dir:
```
../bin/heroics-generate ./example-client-configuration.rb > lib/example-client/client.rb
```

Instead, I see no changes to the `lib/example-client/client.rb` class -- which means that the `ruby_name_replacement_patterns` config isn't doing what it promises.

**Comment by mathias** [comment]
@djcp

**Comment by djcp** [comment]
Please check out: https://github.com/interagent/heroics/pull/84 , which I think fixes the problem with the config not sticking. I'm sure there's a more elegant way to fix this.
