### ISSUE TITLE
off-by-one error in LinkSchema#format_path

### ISSUE THREAD

**Issue by uberjay** [interagent/heroics#88]
While tracking down an exception in `URI.escape` (because of a buggy model class), I ran across a bug in `LinkSchema#format_path`.

The loop over parameters in `format_path` goes one element too far, and attempts to process the body as a parameter. Since there are no further matches for `PARAMETER_REGEX`, the value is discarded.

PR #86 has a fix as well as a unit test.

**Comment by geemus** [comment]
closed by #86
