### ISSUE TITLE
We appear to be overwriting methods in some cases

### ISSUE THREAD

**Issue by djcp** [interagent/heroics#89]
See: https://github.com/heroku/platform-api/pull/61#issuecomment-287915938

and my response here:

https://github.com/heroku/platform-api/pull/61#issuecomment-289029690

It appears we're getting confused about the nested lists under the /organizations/ endpoint and heroics is stomping on the previous `list` method, which got the actual members of an organization.  I'm guessing this has something to do with using a hash internally to track auto-generated methods?

**Comment by wchrisjohnson** [comment]
This has been fixed by https://github.com/interagent/heroics/pull/91, at least in the sense that it raises an issue when duplicate links are discovered.

**Comment by gudmundur** [comment]
@djcp I think this issue is safe to close. We'll be merging fixes to the Platform API schemas to address the duplicates.

**Comment by geemus** [comment]
Got it, thanks for the update.
