### ISSUE TITLE
Duplicate link names 'info', 'update', 'delete'.

### ISSUE THREAD

**Issue by espen** [interagent/heroics#92]
I'm not sure if this is the right repo to report this but as the actual error comes from Heroics I'm going for it.

When upgrading to 0.0.22 I get the following error:

`Duplicate link names 'info', 'update', 'delete'.`

The source of the error is when requiring [heroku autoscaler/heroku_platform_scaler](https://github.com/JustinLove/autoscaler). Which uses [platform-api](https://github.com/heroku/platform-api), which depends on this gem. I see that it now raises an error for [duplicate link names](https://github.com/interagent/heroics/commit/c384f644be308b08da933b181af0a18e1ded5512) but I am unable to find the mentioned names (info, update, delete) in any of the repos here. Only in this repos [test_schema](https://github.com/interagent/heroics/blob/master/test/schema_test.rb#L58).

I appreciate any pointer to finding the source of this.

**Comment by geemus** [comment]
I believe we have now fixed this in the latest platform-api (the errors were in the schema it was using).
